### ISSUE TITLE
Allow port numbers higher than 999

### ISSUE THREAD

**Issue by dotcs** [hansohn/jupyterhub-ldap-authenticator#10]
The [current regex](https://github.com/dotcs/jupyterhub-ldap-authenticator/blob/master/ldapauthenticator/ldapauthenticator.py#L331) that tests the host url only allows port numbers of length 3. 

It's not necessary to use the default port for ldap(s), so port numbers up to 65535 should be valid.

**Comment by hansohn** [comment]
Not sure why auto-close failed for this issue. Changes merged and released as version 0.3.1.
