### ISSUE TITLE
README.md (typo in 'LDAPAuthenticator.group_search_filter' section)

### ISSUE THREAD

**Issue by matteoguglielmi** [hansohn/jupyterhub-ldap-authenticator#12]
This:

c.LDAPAuthenticator.group_search_base =

should be replaced with this:

LDAPAuthenticator.group_search_filter =

**Comment by hansohn** [comment]
Good catch. Documentation has been updated in both master and develop branches. Changes will be included in next release.

**Comment by hansohn** [comment]
Changes have been pushed out. Thanks again!

**Comment by matteoguglielmi** [comment]
👍
