### ISSUE TITLE
Config entries not recognised

### ISSUE THREAD

**Issue by farmerbean** [hansohn/jupyterhub-ldap-authenticator#15]
On start-up; errors -

[W 2019-07-26 08:41:10.213 JupyterHub configurable:168] Config option `bind_dn_template` not recognized by `LDAPAuthenticator`.

[W 2019-07-26 08:41:10.214 JupyterHub configurable:168] Config option `lookup_dn` not recognized by `LDAPAuthenticator`.

[W 2019-07-26 08:41:10.214 JupyterHub configurable:168] Config option `lookup_dn_user_dn_attribute` not recognized by `LDAPAuthenticator`.

**Comment by hansohn** [comment]
These config options are not associated with this code base. Please reference https://github.com/jupyterhub/ldapauthenticator.
