### ISSUE TITLE
User 'foo' is not a member of any permitted groups ['cn=bar,ou=example,c=com']

### ISSUE THREAD

**Issue by petitmermet** [hansohn/jupyterhub-ldap-authenticator#3]
Hi Ryan

I have implemented jupyterhub-ldap-authenticator for jupyterhub. When I try to log in I get a message like below in the log files:

`User 'foo' is not a member of any permitted groups ['cn=bar,ou=example,c=com']`

But this is not true because foo is really a member of this group. Is there an option to disable the allowed_groups feature? Is there an option to show me the list of groups that jupyterhub-ldap-authenticator thinks the user foo is in for debugging? I use the group filter below which works in dokuwiki+ldap:

`c.LDAPAuthenticator.group_search_filter = '(&(objectClass=posixGroup)(|(gidNumber=%{gid})(memberUID=%{user})))'`

Thank you for your help.
Kind regards,
Marc

P.S.: I think there are a few errors in README.md. In the chapters LDAPAuthenticator.group_search_base and LDAPAuthenticator.group_search_filter there is always the parameter c.LDAPAuthenticator.user_search_base...

**Comment by petitmermet** [comment]
Hi Ryan

I've fixed the problem myself. Our LDAP server returns "bar" and not "cn=bar,ou=example,c=com" in auth_user_memberships. So I only needed to change in the configuration

`c.LDAPAuthenticator.allowed_groups = ['cn=bar,ou=example,c=com']`

to

`c.LDAPAuthenticator.allowed_groups = ['bar']`

I had also had the same problem "[KeyError: getpwnam(): name not found: xxxxxxx](KeyError: 'getpwnam(): name not found: xxxxxxx')" as reported in https://github.com/hansohn/jupyterhub-ldap-authenticator/issues/2. I've fixed it, for our use case, by changing

`def user_home_dir_exists(self, username):`
`    """`
`    Verify user home directory exists`
`     """`
`    user = pwd.getpwnam(username)`
`    home_dir = user[5]`
`    return bool(os.path.isdir(home_dir))`

to

`def user_home_dir_exists(self, username):`
`    """`
`    Verify user home directory exists`
`    """`
`    try:`
`        user = pwd.getpwnam(username)`
`        home_dir = user[5]`
`        return bool(os.path.isdir(home_dir))`
`    except KeyError:`
`        return bool(0)`

Thank you for creating jupyterhub-ldap-authenticator.
Regards,
Marc

**Comment by hansohn** [comment]
@petitmermet ,
Thank you for your comments. I fixed some of the issues you mentioned in the latest release including adding the ability to short circuit the `allowed_groups` functionality. Setting the `c.LDAPAuthenticator.allowed_groups` parameter to `None` will enable this short. Out of curiosity, what are you using for your LDAP solution?

Cheers,
Ryan

**Comment by petitmermet** [comment]
Hi Ryan

I have no idea what type of LDAP solution is used. I was just given the necessary information to query it and use jxplorer to figure out the rest myself.

Regards,
Marc
